'training_data_file': 'data/CONLL_NAME_CORPUS_FOR_STUDENTS/CONLL_train.pos-chunk-name'

'development_data_file_x': 'data/CONLL_NAME_CORPUS_FOR_STUDENTS/CONLL_dev.pos-chunk'
'development_data_file_y': 'data/CONLL_NAME_CORPUS_FOR_STUDENTS/CONLL_dev.name'

'testfile': 'data/CONLL_NAME_CORPUS_FOR_STUDENTS/CONLL_test.pos-chunk'
